apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:alpine  # A small, fast Redis image
          ports:
            - containerPort: 6379

---
apiVersion: v1
kind: Service
metadata:
  # This name is CRITICAL. It must match the 'redis_host'
  # in your app.py so Kubernetes can find it.
  name: redis-server
spec:
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    app: redis